/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* "Debug enabled" */
/* #undef DEBUG */

/* Define to 1 if you have the `nodave' library (-lnodave). */
#define HAVE_LIBNODAVE 1

/* PLC's base ip address */
#define IP_BASE_ADDR "10.50.3.22"

/* MPI's address */
#define MPI_ADDR 2

/* Number of PLCs */
#define NPLC 1

/* Name of package */
#define PACKAGE "zefiro"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "Emiliano Giovannetti emiliano.giovannetti@tdt.it"

/* Define to the full name of this package. */
#define PACKAGE_NAME "zefiro"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "zefiro 1.0.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "zefiro"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.0.0"

/* Rack number */
#define RACK 0

/* Daemon's user */
#define RUN_AS_USER "root"

/* CPU's alot */
#define SLOT 2

/* Connection's timeout */
#define TIMEOUT 5000000

/* Version number of package */
#define VERSION "1.0.0"
